models:
  gpt-5.2-2025-12-11:
    type: openai
    model_id: gpt-5.2-2025-12-11
    description: 'gpt-5.2-2025-12-11 (Created: 2025-12-09 15:43 EST)'
  gpt-5.2-chat-latest:
    type: openai
    model_id: gpt-5.2-chat-latest
    description: 'gpt-5.2-chat-latest (Created: 2025-12-10 00:25 EST)'
  dolphin-qwen-3b:
    type: gguf
    repo_id: bartowski/Dolphin3.0-Qwen2.5-3b-GGUF
    filename: Dolphin3.0-Qwen2.5-3b-Q6_K.gguf
    description: bartowski/Dolphin3.0-Qwen2.5-3b-GGUF/Dolphin3.0-Qwen2.5-3b-Q6_K.gguf
      (GGUF)
